### ISSUE TITLE
index.js is too large

### ISSUE THREAD

**Issue by anjannair** [anjannair/Rufus-Discord-Bot#2]
The `index.js` file is very large because of all events being included in that. A separate file for events should be created.

**Comment by InternetRamen** [comment]
I'd like to try this. Can you assign this to me?

**Comment by anjannair** [comment]
> 
> 
> I'd like to try this. Can you assign this to me?

Done!

**Comment by InternetRamen** [comment]
@anjannair #3

**Comment by anjannair** [comment]
Solved thanks to @InternetRamen
