### ISSUE TITLE
Remove Line Reader from Index

### ISSUE THREAD

**Issue by SpiderMath** [anjannair/Rufus-Discord-Bot#61]
In the [index.js](https://github.com/anjannair/Rufus-Discord-Bot/blob/master/index.js) of the project Line [4](https://github.com/anjannair/Rufus-Discord-Bot/blob/master/index.js#L4), you imported the `line-reader` package. But I've checked through out the file, you did not use that, in any part of the code. So I would suggest that, you remove the import for it in Index.js (I know you required it in other files, so I don't think you should uninstall the whole package)

**Comment by anjannair** [comment]
Done thank you!
