### ISSUE TITLE
Better code explanation needed

### ISSUE THREAD

**Issue by anjannair** [anjannair/Rufus-Discord-Bot#7]
Explain all necessary variables and it's functions using the comments for better code understanding

Edit: Don't touch the txt files

**Comment by TijsDeBelie** [comment]
How hard do you want this? And do you want a default template for all code comments?

**Comment by Deepak2417** [comment]
Can you assign this to me?

**Comment by anjannair** [comment]
> How in depth do you want this? And do you want a default template for all code comments? 
> Do you want code comments for every variable used? And/or do you want only on the most important ones? 
> 
> Do you want to have some small rewrites of the code to make it better? I already saw some variables being declared but only used once which can be circumvented. 
> 
> If this is the goal a new issue could be made to improve code quality

@TijsDeBelie yes all of the above! I would love the code quality to be improved
